### ISSUE TITLE
Custom scrolling wrapper (not body)

### ISSUE THREAD

**Issue by forever-z-133** [electerious/basicScroll#10]
my English is not good, just do my best.

```
.body {
    position: absolute;
    top: 0; bottom: 0;
    left: 0; right: 0;
    display: flex;
    flex-direction: column;
    max-width: 768px;
    margin: auto;
}
.main {
    flex-grow: 1;
    overflow-x: hidden;
    overflow-y: auto;
    transform: translate3d(0,0,0);
    -webkit-overflow-scrolling: touch;
}
```
```
<div class="body">
  <div class="main">
      // my code
  </div>
</div>
```
like this, the scrolling wrapper is not body.

so can you add an option (like 'wrap') to fit it?

**Comment by ozasadnyy** [comment]
+1. I also need to listen to another scroll container.

**Comment by electerious** [comment]
This is currently not planned, but I will leave the issue open to see if more people are interested in this feature.

**Comment by joakimgreen** [comment]
**+1** I would use this in a project as well. (Currently using a scrollable `100vh` container for the main content)

@electerious: Really like basicScroll, awesome work Tobias!

**Comment by frankharrison-wj** [comment]
+1 for this!

**Comment by chrisrowe** [comment]
Thanks! +1 also on this

**Comment by cpouldev** [comment]
+1, by integrating  https://github.com/idiotWu/smooth-scrollbar, the overall scroll & parallax experience will be perfect

**Comment by cpouldev** [comment]
Managed to get it working with smooth-scrollbar. I've added an argument to `create` function, so a condition on `getScrollTop()` decides whether to use its default behaviour or whatever function you pass on it. I've added a function which returns the custom scroll body position and it works flawlessly. The result is wonderful!

**Comment by martinsnajdr** [comment]
@hambos22 Any chance you could send me your tweaked source code for the smooth-scrollbar compatible version of basic-scroll?!

Thank you very much :)

**Comment by cpouldev** [comment]
@martinsnajdr here https://github.com/hambos22/basicScroll/blob/master/src/scripts/main.js#L58

And then you do on basicScroll initialisation 
```
basicScroll(data, {
      enabled: true,
      scrollTop() {
        return scrollbar.offset.y
      },
    });
```

**Comment by martinsnajdr** [comment]
@hambos22 Thank you, you helped me a lot!

**Comment by charlesbeaumont** [comment]
+1 for this feature.

**Comment by louisameline** [comment]
+1

**Comment by electerious** [comment]
The provided implementation as mentioned by @cpuldev only works when the custom container has no offset to the top of the body. It also changes all instances to that custom container.

A sophisticated solution would allow a custom scrolling root for each instance that takes the top position into account, updates when the root scrolls and recalculates the properties of the instance when the size changes.

**All this is not possible with the current implementation and would require a complete rewrite of basicScroll. That's why this feature sadly won't be part of basicScroll in the future.**
