### ISSUE TITLE
New Property Request: Assign Different Target Element for Scroll Position

### ISSUE THREAD

**Issue by katiehhuffman** [electerious/basicScroll#11]
I recently discovered this library and **love** that it uses CSS variables - it's exactly what I've been looking for. However, I've hit a road block with the API while attempting to directly apply `props[]` variables to an array of elements while using a different element (i.e. the parent) as the scroll trigger.

My request is to create a new property, maybe called `anchor` or `target`, that allows you to listen to the scroll of a different element than what the directly applied `props[]` styles are assigned to.

**Example:**
```html
<div class="foo">
    <div class="bar"></div>
</div>
```
```js
const instance = basicScroll.create({
	target: document.querySelector('.bar'),    // this property assigns the scroll listener  
	from: 'top-bottom',    // start position relative to the 'target' property (or 'elem' if no target is assigned)
	to: 'bottom-top',    // end position relative to the 'target' property (or 'elem' if no target is assigned)
	elem: document.querySelector('.bar'),    // this property assigns where the 'props[]' are applied
	direct: true,    // apply props[] locally to 'elem'
	props: {
		'--ty': {
			from: 0,
			to: 100,
		}
	}
})
```
**My recommendations:** 
This property would be optional and the default value is `null`. 
If no value is given and `elem !== null` then the script would assume `target == elem`.
The property `elem` is required when `target` has a value.

**For reference:**
[skrollr#relative-mode-or-viewport-mode](https://github.com/Prinzhorn/skrollr#relative-mode-or-viewport-mode) gives the option to use `data-anchor-target` attribute when another element's position should trigger the assigned element's keyframes.

(**Side Note:** I was a huge fan of skrollr for years but had to eventually come to terms with the fact it was never going to be updated again... so my only option was to switched to Scrollmagic + GSAP. However, I have been less than pleased with the performance and overall API... Which means adding this property to basicScroll would be a game changer for me.)

**Comment by electerious** [comment]
We could use the `direct` property for it. It could be `false`, `true` or an element to use instead of `elem`.

`false` = Apply `props[]` globally
`true` = Apply `props[]` to `elem`
`Node` = Apply `props[]` to `Node` element

**Comment by katiehhuffman** [comment]
@electerious If what you're proposing is the fastest/most efficient solution, then that works for me. API implementation should be pretty straight forward since the purpose of the `direct` property is to decide where the variables are applied.

To clarify (in case users reference this thread in the future) - what you outlined contradicts the current `true` / `false` definitions for the `direct` property. Do you mean the following?

`false` = Apply `props[]` globally
`true` = Apply `props[]` to `elem`

**Comment by electerious** [comment]
You're right. Thanks for letting me know. I've fixed it.

Adding support for a Node element in the `direct` property would be the way to go.

**Comment by electerious** [comment]
Just released a pre-version of 2.1. You can try it with `npm install basicscroll@next`. Please take a look at the documentation and let me know if it is clear or if there's anything I can improve: https://github.com/electerious/basicScroll/tree/develop#direct-mode

**Comment by katiehhuffman** [comment]
Tested pre-version 2.1 and the change to `direct` works as expected.

The documentation's definition of the new value option is concise as well. My only change is to update the Type from `Boolean` to `Boolean|String`.

Thank you for quickly knocking out this update!

**Comment by electerious** [comment]
Well spotted. I've changed it to `Boolean|Node`!

**Comment by electerious** [comment]
[v2.1.0](https://github.com/electerious/basicScroll/pull/14) is out.
