### ISSUE TITLE
Polyfill for custom properties 

### ISSUE THREAD

**Issue by TomS-** [electerious/basicScroll#18]
The only Polyfill I can find is https://github.com/postcss/postcss-custom-properties
As this is set during the build process basicScroll will not work. Which Polyfill do you recommend to work with basicScroll?

**Comment by electerious** [comment]
It's not possible to polyfill css custom properties in a way that would work with basicScroll. I generally recommend to add parallax animations / effects as a gimmick for users with modern browsers. Users with older browser should see the site without those effects, but still get a functional site.

basicScroll can also animate normal properties. This might be helpful if you want to support older browsers.

**Comment by stratboy** [comment]
Maybe this one?

https://github.com/jhildenbiddle/css-vars-ponyfill

**Comment by nuxodin** [comment]
Or try this one:
https://github.com/nuxodin/ie11CustomProperties
