### ISSUE TITLE
Disable basicScroll on mobile devices?

### ISSUE THREAD

**Issue by MonsterDeveloper** [electerious/basicScroll#20]
Is there any option to disable basicScroll on mobile devices?

**Comment by electerious** [comment]
No, but there're multiple ways to do what you're looking for:

a) Use media-queries in your CSS to disable the use of animated CSS properties
b) Never call `.start` on mobile devices
c) Call `.stop()` on mobile devices

I recommend to use the first option.

**Comment by FynnZW** [comment]
I noticed that for iOS Safari, I have to destroy the instance. Not calling start is not enough:
```js
 // init above
  if (window.innerWidth >== 640) {
    parallaxElements.forEach((parallaxElement) => parallaxElement.start())
  } else {
    parallaxElements.forEach((parallaxElement) => parallaxElement.destroy())
  }
```
