### ISSUE TITLE
Mobile background position

### ISSUE THREAD

**Issue by peterlunglum** [electerious/basicScroll#23]
Not sure if this is a bug or if there's a fix for this or not, but trying to scroll on mobile to change the background position from the bottom of a background image to the top. On desktop it scrolls as anticipated from the bottom of the image upwards, but on mobile, it defaults to the top of the background image position and scrolls to the bottom as per normal behavior. Is there a reason for this or a fix?

**Comment by electerious** [comment]
Can you provide some example code?
