### ISSUE TITLE
Can I use old school javascript?

### ISSUE THREAD

**Issue by stratboy** [electerious/basicScroll#33]
Hi, great script, and I'd like to use! :) But i'm still old-school javascript, so for now I'm not doing transpiling. I see you're using modern js syntax like `const` and `arrow functions` and the like. Is it still possible to use it with plain old school syntax?

**Comment by electerious** [comment]
The dist folder contains the transpiled JS that comes without const and arrow functions: https://github.com/electerious/basicScroll/blob/master/dist/basicScroll.min.js

**Comment by stratboy** [comment]
Thank you

Tobias Reich ha scritto:

**Comment by stratboy** [comment]
I just found out that this will work properly, but won't log anything in console under the `inside` hook:

``` js
var speed_parallax_bg = document.querySelector('.section.speed .parallax-bg');
var speed_parallax = basicScroll.create({
  elem: speed_parallax_bg,
  from: 'top-bottom',
  to: 'bottom-top',
  props: {
    '--speed-bg-scrolled': {
      from: '0'
      ,to: '-34%'
      ,timing: 'quadInOut'
      ,inside: function(instance, percentage, props){
        console.log(instance, percentage, props); // TEST LOG
      }
    }
  }
})

speed_parallax.start();
```

**Comment by electerious** [comment]
You need to start the instance with `speed_parallax.start()`

**Comment by stratboy** [comment]
No excuse me, I'm already doing it, I update my post. Still it works, except that it doesn't log.

**Comment by stratboy** [comment]
Solved the log thing: the issue here was that I was putting the inside prop under props, while it should be putted outside the props.

``` js
var speed_parallax_bg = document.querySelector('.section.speed .parallax-bg');
var speed_parallax = basicScroll.create({
  elem: speed_parallax_bg,
  from: 'top-bottom',
  to: 'bottom-top',
  props: {
    '--speed-bg-scrolled': {
      from: '0'
      ,to: '-34%'
      ,timing: 'quadInOut'
    },
  },
  inside: function(instance, percentage, props){
     console.log(instance, percentage, props); // TEST LOG
  }
})

speed_parallax.start();
```
