### ISSUE TITLE
Add typescript

### ISSUE THREAD

**Issue by jantimon** [electerious/basicScroll#36]
This library is amazing :)

Would you be up to add typescript for better code quality and easier usage?

That way it would also be possible to ship an additional smaller version of this library which would not validate the parameters  during runtime.

**Comment by electerious** [comment]
Glad you like basicScroll! :)

TypeScript is not planned as I'm not a TypeScript user and therefore not willed to maintain it.

**Comment by jantimon** [comment]
Okay that’s something I can understand - if you would add some more jsdoc comments that would already be enough for typescript to understand your library.. I could prepare a pull request if that would be interesting for you

**Comment by electerious** [comment]
That would be cool. Better jsdoc comments are always welcome!

**Comment by jantimon** [comment]
Cool in that case i’ll look into it and will
let you know once I have a pull request to show

**Comment by jantimon** [comment]
Hey @electerious I added a pull request which will go very in detail and explain the details behind all those `object` arguments:

https://github.com/electerious/basicScroll/pull/37
