### ISSUE TITLE
Issue when scrolling too fast

### ISSUE THREAD

**Issue by fredericpfisterer** [electerious/basicScroll#44]
Hello,

I noticed that when I use the inside callback, If I scroll too fast it will stop around 60% instead of 100% and prevent my animation to finish properly. Is there anyway it could be fixed ?

Cheers

**Comment by fredericpfisterer** [comment]
I created a codepen so you can see the issue :

https://codepen.io/fredericpfisterer/pen/zQLqVv

**Comment by electerious** [comment]
You could try to re-render your animation when the `inside` and `outside` callback fires, instead of just using the `inside` callback. This way you would know when the percentage is above 100% or below 0%, even when the users scrolls fast.

Is that something that could work?

**Comment by fredericpfisterer** [comment]
Yes, That's what I ended up doing. But it would be useful to be able to use percentage just with the inside callback :)

**Comment by JiveDig** [comment]
@fredericpfisterer Can you post an updated CodePen showing what the solution to this was?
