### ISSUE TITLE
Homepage Documentation incorrect

### ISSUE THREAD

**Issue by TomS-** [electerious/basicScroll#47]
https://basicscroll.electerious.com/

In the example: 
```
   from: 'top-top',
   to: 'bottom-bottom',
```
It can't start from the top and end at the bottom of the viewport. It should start at the bottom and end at the top. So from: 'top-bottom' and to 'bottom-top'.

**Comment by electerious** [comment]
True. They are swapped. It should be

```
from: 'bottom-bottom',
to: 'top-top',
```

Thanks for letting me know.
