### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by steveooo9** [electerious/basicScroll#5]
What's the browser support? Nothing mentioned there. Does this work when browser do not have CSS variables?

**Comment by bovas85** [comment]
As you can see here support is quite evergreen good
https://caniuse.com/#feat=css-variables
Unless you need IE11 support, in that case it will probably fail.

**Comment by electerious** [comment]
The requirements are [documented in the readme](https://github.com/electerious/basicScroll#requirements). I recommend [Can I Use](https://caniuse.com) to check if your required browser supports all features.

basicScroll can also animate normal properties. This might be helpful if you want to support IE11.
