### ISSUE TITLE
Multiple start and stop positions

### ISSUE THREAD

**Issue by dhruveonmars** [electerious/basicScroll#52]
Is it possible to create something similar to this ([https://p2mv.studio/about](https://p2mv.studio/about)) using basicScroll? Or would a more custom scroll need to be created?
I don't have to create exactly that, but that's the reference I have to work off.

I imagine if it was possible, it would be using multiple custom values in for the start and stop positions, but not quite sure.

Any help is appreciated

**Comment by electerious** [comment]
I don't think that basicScroll is the right tool to create such a scroll effect. There's no real start and stop position. It's more like tracking the scroll position of the site and applying the offset as a transform to the elements (+ a delay).
