### ISSUE TITLE
Resize Issue

### ISSUE THREAD

**Issue by rjsandman** [electerious/basicScroll#54]
Hello,

When resizing my screen it seems to throw off my scroll animation.  I'm using Svelte as my framework so I'm not sure if there is something I need to do in order to get it to work.  The animation still works but it seems to throw off the from and to numbers.

**Comment by electerious** [comment]
basicScroll tracks the window position and updates the instances when necessary. If that update fails for some reason you can do it manually:

```js
instance.calculate()
instance.update()
```

You can turn off the [`track` option](https://github.com/electerious/basicScroll#data) in this case.
