### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by bovas85** [electerious/basicScroll#6]
I use Nuxt and SPA behaviour and would like to know how to restart it (or destroy - recreate) on each route change as the method will stay alive globally but won't move the element anymore as the reference changed.

**Comment by electerious** [comment]
It's currently not possible to destroy an instance, but you can call `instance.stop()` and basicScroll will stop animating it. `instance.remove()` might be a good addition. Thanks for the idea.

**Comment by bovas85** [comment]
No probs, that'd be fantastic as at the moment whenever I move to another dynamic route it will duplicate the instance and block the animation

**Comment by electerious** [comment]
Added a destroy function :) Could you please make a review of the code changes? Will make it part of the next release when everything is fine.

https://github.com/electerious/basicScroll/commit/3976d72b718ee6306a6ea5479ba1c7065f9817b7

**Comment by bovas85** [comment]
shouldn't _destroy have an argument of index?

**Comment by electerious** [comment]
Not required. The index is part of there instance: https://github.com/electerious/basicScroll/commit/3976d72b718ee6306a6ea5479ba1c7065f9817b7#diff-e7ec20b0ed49ebd35a3718a4a5838760R374

**Comment by electerious** [comment]
New version is live: https://github.com/electerious/basicScroll/commit/491d6c56db8be1a8e147220504cac059d9257d27

**Comment by bovas85** [comment]
Ah I see :) good stuff will test it on Monday
