### ISSUE TITLE
[Feature] Option to set custom "scrolling element"

### ISSUE THREAD

**Issue by hakimio** [electerious/basicScroll#61]
There are some cases when "scrolling element" is neither `document.scrollingElement`, nor `document.documentElement`. For example, when using web components with shadow root or `Ionic framework` components which are also built on top of web components. You can check [ion-content](https://ionicframework.com/docs/api/content) component to see how it works.

It would be really nice if it was possible to manually specify the "scrolling element" when creating new `basicScroll` instances.

**Comment by hakimio** [comment]
@electerious if you are busy, I could make a PR.

**Comment by electerious** [comment]
I remember that there wasn't a good solution to do so: https://github.com/electerious/basicScroll/issues/10#issuecomment-449143806

But the comment is a few years old. Maybe there's a better way now. I will close this issue, but I'm open for a PR :)
