### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by chrisvidal** [electerious/basicScroll#62]
Is there any documentation to understand the meaning of please :

```
from: 'top-middle',
to: 'bottom-middle',
```

and other options?

**Comment by electerious** [comment]
Yes, you can find it in [the documentation](https://github.com/electerious/basicScroll#start-and-stop-position).

**Comment by chrisvidal** [comment]
yes I saw that, but it does not explain the behavior of each of them.

**Comment by electerious** [comment]
> `<element>-<viewport>`. `middle-bottom` in `from` specifies that the animation starts when the middle of the element reaches the bottom of the viewport.

It's the same for the other values. Here're a few examples:

`bottom-bottom` in `from` specifies that the animation starts when the bottom of the element reaches the bottom of the viewport.
`middle-top` in `from` specifies that the animation starts when the middle of the element reaches the top of the viewport.

Hope that helps! :)

**Comment by chrisvidal** [comment]
got it, thanks a bunch!
