### ISSUE TITLE
Get instance element in callback?

### ISSUE THREAD

**Issue by maubut** [electerious/basicScroll#8]
Hey,

What a cool library! I'm trying to figure out a way i could add or remove classes to my element from the callback (inside and outside)? Is there a way i could do like:

```
outside: (instance, percentage, props) => {
    console.log('viewport is outside from and to');
    instance.elem.classList.add('active');
}
```

**Comment by christophemarois** [comment]
@mikoelsuperbeasto  you can already do it with the `instance.getData()` function

```javascript
inside: (instance, percentage, props) => {
  const elem = instance.getData().elem
  elem.classList.add('something')
}
```

**Comment by maubut** [comment]
Cool thanks you!
